// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GpgsIds
{
        public const string achievement_zombie_like_a_rock_star = "CgkI6vSnha0eEAIQBQ"; // <GPGSID>
        public const string achievement_zombie_on_a_roll = "CgkI6vSnha0eEAIQAw"; // <GPGSID>
        public const string achievement_zombie_on_the_top_of_world = "CgkI6vSnha0eEAIQBg"; // <GPGSID>
        public const string leaderboard_score = "CgkI6vSnha0eEAIQAQ"; // <GPGSID>
        public const string achievement_zombie_having_a_blast = "CgkI6vSnha0eEAIQBA"; // <GPGSID>
        public const string achievement_zombie_dead_in_rush = "CgkI6vSnha0eEAIQAg"; // <GPGSID>

}

